baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Konst_Vatruba"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
name = "Konstantin Vatruba"

[params]
author = "Konstantin Vatruba"
description = "Konstantin's personal website."
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
mathjax = false

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional
  
[[params.social]]
id = "twitter"
url = "https://https://twitter.com/Konst_Vatruba/"

[[params.social]]
id = "github"
url = "https://github.com/konstvatruba/"

[languages.en]
languageName = "Русский"

[[menu.main]]
identifier = "about"
name = "Обо мне"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Тэги"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Архив"
identifier = "archive"
url = "/posts/"
weight = 3

[languages.es]
languageName = "Español"

[[languages.es.menu.main]]
identifier = "about"
name = "Acerca de mi"
url = "/about/"
weight = 1

[[languages.es.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[languages.es.menu.main]]
identifier = "archive"
name = "Archivo"
url = "/posts/"
weight = 3

[[languages.es.params]]
locale = "es-es"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup.goldmark.renderer]
unsafe = true
